"use client";

import { useEffect, useMemo, useState } from "react";

type RecordRow=Record<string,string>;
type Source={id:string;category:string;title:string;datasetUrl:string;resourceUrl:string;format:string;modified:string;recordCount:number|null;status:string};
type Payload={status:string;province:string;policy:string;fetchedAt:string;sources:Source[];data:Record<string,RecordRow[]>;errors:string[];decisionGate:{status:string;reason:string}};
type View="decision"|"inventory"|"explorer";

const empty:Payload={status:"loading",province:"น่าน",policy:"Official data only · No mock values",fetchedAt:"—",sources:[],data:{},errors:[],decisionGate:{status:"insufficient",reason:"กำลังตรวจสอบความเพียงพอของข้อมูลทางการ"}};
const number=(value:string|undefined)=>Number((value??"0").replace(/[ ,]/g,""))||0;
const categories:Record<string,{label:string;icon:string}>={tourism:{label:"การท่องเที่ยว",icon:"◎"},attraction:{label:"สถานที่ท่องเที่ยว",icon:"⌖"},accommodation:{label:"ที่พัก",icon:"⌂"},food:{label:"อาหารและร้านอาหาร",icon:"◉"},transport:{label:"การขนส่ง",icon:"↗"},culture:{label:"ประเพณีและวัฒนธรรม",icon:"◇"},"local-business":{label:"ผลิตภัณฑ์และร้านค้าชุมชน",icon:"◆"}};

function useOfficialNan(){
  const [data,setData]=useState<Payload>(empty); const [run,setRun]=useState(0);
  useEffect(()=>{const controller=new AbortController();setData(empty);fetch("/api/official-nan",{signal:controller.signal}).then(async response=>{const body=await response.json();if(!response.ok&&response.status!==206)throw new Error(body.message??"Official source failed");return body;}).then(setData).catch(error=>{if(error.name!=="AbortError")setData({...empty,status:"error",errors:[error.message]});});return()=>controller.abort();},[run]);
  return {data,refresh:()=>setRun(value=>value+1)};
}

function SourceStatus({source}:{source:Source}){return <a className="official-source-card" href={source.datasetUrl} target="_blank" rel="noreferrer"><span>{categories[source.category]?.icon??"○"}</span><div><small>{categories[source.category]?.label??source.category}</small><strong>{source.title}</strong><p>{source.format} · อัปเดต {source.modified}</p></div><em className={`source-${source.status}`}>{source.status}{source.recordCount!==null?` · ${source.recordCount.toLocaleString()}`:""}</em><b>↗</b></a>}

function DecisionView({payload}:{payload:Payload}){
  const tourism=payload.data.tourism??[];
  const latest=tourism.filter(row=>row["ประเภท"]==="ผู้เยี่ยมเยือน").sort((a,b)=>number(a["ปี"])-number(b["ปี"])).at(-1);
  const previous=tourism.filter(row=>row["ประเภท"]==="ผู้เยี่ยมเยือน").sort((a,b)=>number(a["ปี"])-number(b["ปี"])).at(-2);
  const total=number(latest?.["รวม"]), prior=number(previous?.["รวม"]), change=prior?((total-prior)/prior*100):0;
  const csvConnected=payload.sources.filter(source=>source.status==="connected").length;
  return <div className="official-stack">
    <section className="official-hero"><div><p className="official-eyebrow">Today’s Decision · Official Evidence Only</p><h1>ยังไม่อนุมัติ<br/>การกระจายนักท่องเที่ยว</h1><p>AI หยุดการ Execute เพราะข้อมูลจาก data.go.th ยังไม่มี Community Need, Capacity และ Tourist Density ระดับชุมชนในเวลาปัจจุบัน</p></div><div className="decision-lock"><span>!</span><strong>Insufficient Evidence</strong><small>Human review required</small></div></section>
    <section className="evidence-status"><div className="status-head"><div><p className="official-eyebrow">Official Data Connection</p><h2>ข้อมูลที่ระบบรับได้จริง</h2></div><span className={`connection-${payload.status}`}>{payload.status==="connected"?"● Connected":payload.status==="loading"?"● Connecting":"● Partial"}</span></div><div className="evidence-numbers"><article><strong>{csvConnected}</strong><span>Structured datasets connected</span></article><article><strong>{payload.sources.filter(source=>source.status==="reference").length}</strong><span>Official PDF references</span></article><article><strong>{payload.sources.reduce((sum,source)=>sum+(source.recordCount??0),0).toLocaleString()}</strong><span>Official records loaded</span></article><article><strong>0</strong><span>Mock records used</span></article></div></section>
    <section className="official-tourism-baseline"><div><p className="official-eyebrow">Official Tourism Baseline</p><h2>สถิตินักท่องเที่ยวจังหวัดน่าน</h2><span>ชุดข้อมูลจริงจากสำนักงานจังหวัดน่าน</span></div><div><article><small>ปีล่าสุด</small><strong>{latest?.["ปี"]??"—"}</strong><span>พ.ศ.</span></article><article><small>ผู้เยี่ยมเยือนรวม</small><strong>{total?total.toLocaleString():"—"}</strong><span>{latest?.["หน่วย"]??"ราย"}</span></article><article><small>ชาวไทย</small><strong>{number(latest?.["ชาวไทย"])?number(latest?.["ชาวไทย"]).toLocaleString():"—"}</strong><span>ราย</span></article><article><small>การเปลี่ยนแปลง</small><strong>{prior?`${change>=0?"+":""}${change.toFixed(1)}%`:"—"}</strong><span>เทียบปีก่อนหน้า</span></article></div></section>
    <section className="decision-gaps"><div><p className="official-eyebrow">AI Decision Gate</p><h2>ข้อมูลที่ต้องมีก่อนตัดสินใจ</h2></div><div><article><span>01</span><strong>Community Need</strong><p>data.go.th ยังไม่มีความต้องการปัจจุบันรายชุมชน</p></article><article><span>02</span><strong>Community Capacity</strong><p>ยังไม่มีจำนวนที่รับได้จริงของกิจกรรมและชุมชน</p></article><article><span>03</span><strong>Live Density</strong><p>มีสถิติระดับจังหวัด แต่ไม่มีความหนาแน่นปัจจุบันรายพื้นที่</p></article><article><span>04</span><strong>Verified Impact</strong><p>ยังไม่มีรายได้จริงหลังแคมเปญระดับครัวเรือน</p></article></div><button disabled>Execute ถูกปิดจนกว่าข้อมูลครบ</button></section>
  </div>
}

function InventoryView({payload}:{payload:Payload}){
  const attractions=payload.data.attractions??[],stays=payload.data.stays??[],restaurants=payload.data.restaurants??[];
  const districts=useMemo(()=>{const map=new Map<string,{attractions:number;stays:number;restaurants:number}>();const add=(district:string,key:"attractions"|"stays"|"restaurants")=>{const name=district||"ไม่ระบุอำเภอ";const item=map.get(name)??{attractions:0,stays:0,restaurants:0};item[key]++;map.set(name,item)};attractions.forEach(row=>add(row["อำเภอ/เขต"],"attractions"));stays.forEach(row=>add(row["อำเภอ"],"stays"));restaurants.forEach(row=>add(row["อำเภอ/เขต"],"restaurants"));return [...map.entries()].map(([district,counts])=>({district,...counts,total:counts.attractions+counts.stays+counts.restaurants})).sort((a,b)=>b.total-a.total);},[attractions,stays,restaurants]);
  return <div className="official-stack"><header className="official-page-head"><div><p className="official-eyebrow">Nan Official Inventory</p><h1>ทรัพยากรท่องเที่ยว<br/>ที่มีหลักฐานทางการ</h1></div><p>รวมข้อมูลสถานที่ท่องเที่ยว ที่พัก และร้านอาหารจากชุดข้อมูลจังหวัดน่านเท่านั้น จำนวนคือจำนวนระเบียนใน resource ไม่ใช่ Capacity</p></header><section className="inventory-summary"><article><span>⌖</span><strong>{attractions.length.toLocaleString()}</strong><small>แหล่งท่องเที่ยว</small></article><article><span>⌂</span><strong>{stays.length.toLocaleString()}</strong><small>สถานพักแรม</small></article><article><span>◉</span><strong>{restaurants.length.toLocaleString()}</strong><small>ร้านอาหาร</small></article><article><span>◎</span><strong>{districts.length}</strong><small>อำเภอที่พบในข้อมูล</small></article></section><section className="district-table"><div className="table-head"><h2>การกระจายทะเบียนตามอำเภอ</h2><span>Official record count · ไม่ใช่ Demand</span></div><div className="district-row district-label"><span>อำเภอ</span><span>แหล่งท่องเที่ยว</span><span>ที่พัก</span><span>ร้านอาหาร</span><span>รวมระเบียน</span></div>{districts.map(item=><div className="district-row" key={item.district}><strong>{item.district}</strong><span>{item.attractions}</span><span>{item.stays}</span><span>{item.restaurants}</span><b>{item.total}</b></div>)}</section></div>
}

function ExplorerView({payload}:{payload:Payload}){
  const [category,setCategory]=useState("all"),[query,setQuery]=useState("");
  const collections=[...(payload.data.attractions??[]).map(row=>({category:"attraction",title:row["ชื่อสถานที่ (ภาษาไทย)"],detail:row["อำเภอ/เขต"],meta:"แหล่งท่องเที่ยว"})),...(payload.data.stays??[]).map(row=>({category:"accommodation",title:row["ชื่อสถานพักแรม" ]||row["ชื่อสถานพักแรม "],detail:row["อำเภอ"],meta:row["ประเภทที่พัก"]})),...(payload.data.restaurants??[]).map(row=>({category:"food",title:row["ชื่อสถานที่ (ภาษาไทย)"],detail:row["อำเภอ/เขต"],meta:row["ประเภทอาหาร"]})),...(payload.data.transport??[]).map(row=>({category:"transport",title:row["ประเภทรถ"],detail:`${row["ปี"]} · ${row["จำนวน"]} ${row["หน่วย"]}`,meta:"ทะเบียนรถโดยสาร"}))];
  const filtered=collections.filter(item=>(category==="all"||item.category===category)&&`${item.title} ${item.detail} ${item.meta}`.toLowerCase().includes(query.toLowerCase())).slice(0,120);
  return <div className="official-stack"><header className="official-page-head"><div><p className="official-eyebrow">Official Data Explorer</p><h1>ค้นหาข้อมูลจริง<br/>ภายในจังหวัดน่าน</h1></div><p>ผลลัพธ์ทุกแถวมาจาก resource ที่ลงทะเบียนใน data.go.th ไม่มี Caption, Rating, Capacity หรือ Impact ที่สร้างขึ้นเอง</p></header><section className="explorer-controls"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="ค้นหาชื่อ อำเภอ ประเภทอาหาร หรือประเภทรถ"/><div>{["all","attraction","accommodation","food","transport"].map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item==="all"?"ทั้งหมด":categories[item]?.label}</button>)}</div></section><section className="official-records"><div className="records-head"><strong>{filtered.length.toLocaleString()}</strong><span>รายการที่แสดง · จำกัด 120 รายการต่อหน้า</span></div><div>{filtered.map((item,index)=><article key={`${item.category}-${item.title}-${index}`}><span>{categories[item.category]?.icon}</span><div><small>{categories[item.category]?.label}</small><strong>{item.title||"ไม่ระบุชื่อ"}</strong><p>{item.meta||"—"} · {item.detail||"ไม่ระบุอำเภอ"}</p></div></article>)}</div></section><section className="source-register-official"><div><p className="official-eyebrow">Data Provenance</p><h2>แหล่งข้อมูลที่ระบบเรียกใช้</h2></div><div>{payload.sources.map(source=><SourceStatus source={source} key={source.id}/>)}</div></section></div>
}

export function OfficialNanApp(){
  const {data,refresh}=useOfficialNan(); const [view,setView]=useState<View>("decision");
  return <main className="official-shell"><aside><div className="official-brand"><span>AI</span><div><strong>Nan Pulse AI</strong><small>Official Data Mode</small></div></div><nav>{([{id:"decision",label:"Decision Gate",note:"หลักฐานก่อนตัดสินใจ",icon:"◎"},{id:"inventory",label:"Nan Inventory",note:"ทรัพยากรรายอำเภอ",icon:"⌖"},{id:"explorer",label:"Official Explorer",note:"ค้นหาระเบียนทางการ",icon:"↗"}] as const).map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><span>{item.icon}</span><div><strong>{item.label}</strong><small>{item.note}</small></div></button>)}</nav><div className="official-policy"><span>0</span><strong>Mock records</strong><small>data.go.th only</small></div></aside><section className="official-main"><header className="official-topbar"><div><span className={`api-dot api-${data.status}`}/><strong>{data.status==="loading"?"กำลังเชื่อม data.go.th":data.status==="connected"?"Official sources connected":"Official sources partial"}</strong><small>{data.fetchedAt==="—"?"—":new Date(data.fetchedAt).toLocaleString("th-TH")}</small></div><button onClick={refresh}>อัปเดตข้อมูล ↻</button></header><div className="official-content">{view==="decision"&&<DecisionView payload={data}/>} {view==="inventory"&&<InventoryView payload={data}/>} {view==="explorer"&&<ExplorerView payload={data}/>}</div></section></main>
}
